version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  node:
    image: node:18
    container_name: laravel_node
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge